/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_profile"];
        put: operations["put_profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["today"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DailyTargetView: {
            /** Format: double */
            kcal: number;
            /** Format: double */
            protein_g: number;
        };
        /** @description JSON shape of every error response. */
        ErrorBody: {
            /** @description Stable machine-readable error code (e.g. `not_found`, `unauthorized`). */
            error: string;
            /** @description Human-readable error message. */
            message: string;
        };
        HealthResponse: {
            status: string;
        };
        HistoryResponse: {
            /** Format: date-time */
            from: string;
            measurements: components["schemas"]["MeasurementView"][];
            /** Format: date-time */
            to: string;
        };
        MeResponse: {
            email: string;
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** @description Wire shape of a single measurement. */
        MeasurementView: {
            /** Format: double */
            body_fat_percent?: number | null;
            /** Format: double */
            lean_mass_kg?: number | null;
            /** @description Provenance of the reading. One of: `withings`, `manual`. */
            source: string;
            /** Format: date-time */
            taken_at: string;
            /** Format: double */
            weight_kg: number;
        };
        ProfilePayload: {
            /** @description One of: `sedentary`, `lightly_active`, `moderately_active`, `very_active`. */
            activity_level: string;
            /** Format: date */
            birth_date: string;
            /** Format: double */
            goal_weight_kg: number;
            /** Format: double */
            height_cm: number;
            /** @description One of: `male`, `female`. */
            sex: string;
        };
        ProfileView: {
            /** @description One of: `sedentary`, `lightly_active`, `moderately_active`, `very_active`. */
            activity_level: string;
            /** Format: date */
            birth_date: string;
            /** Format: double */
            goal_weight_kg: number;
            /** Format: double */
            height_cm: number;
            /** @description One of: `male`, `female`. */
            sex: string;
        };
        TodayResponse: {
            /** Format: double */
            bmi?: number | null;
            daily_target?: null | components["schemas"]["DailyTargetView"];
            latest?: null | components["schemas"]["MeasurementView"];
            user: components["schemas"]["UserView"];
            /** Format: double */
            weekly_delta_kg?: number | null;
        };
        TrendResponse: {
            /** Format: date-time */
            from: string;
            measurements: components["schemas"]["MeasurementView"][];
            /** Format: double */
            moving_average_7d_kg?: number | null;
            /** Format: date-time */
            to: string;
            /** Format: double */
            weekly_delta_kg?: number | null;
        };
        UserView: {
            email: string;
            /** Format: uuid */
            id: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    history: {
        parameters: {
            query: {
                /** @description Inclusive lower bound (RFC 3339). */
                from: string;
                /** @description Exclusive upper bound (RFC 3339). */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Measurements in `[from, to)` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Invalid window */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Missing or invalid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Missing or invalid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Missing or invalid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Profile not yet set */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    put_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePayload"];
            };
        };
        responses: {
            /** @description Profile saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Missing or invalid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    today: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Today's KPIs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayResponse"];
                };
            };
            /** @description Missing or invalid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    trend: {
        parameters: {
            query?: {
                /** @description Window length in days (default 30, max 365). */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Measurements + aggregate stats over the window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description `days` out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Missing or invalid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
